name: Deploy to WP Engine
on:
  push:
    branches:
     - production
jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: hopeisreal
        # Deploy Options
        SRC_PATH: "."
        REMOTE_PATH: "wp-content/plugins/bc-adverts-twd/"
        FLAGS: "-azvr --delete"
        CACHE_CLEAR: true
        SCRIPT: |
        # make absolutely sure the plugin folder exists
        mkdir -p wp-content/plugins/bc-adverts-twd